language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - mixj93@163.com
    on_success: change # default: change
    on_failure: always # default: always

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
# - npm install -g gulp

script:
  # - hexo clean
  - hexo generate -b

after_script:
  - git config user.name "mixj93"
  - git config user.email "mixj93@163.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle
